### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stefanv** [jabbalaci/Bash-Utils#2]
Please license the material in this repository so that it can be reused.

Thank you for writing these!

**Comment by jabbalaci** [comment]
MIT license added.
I want to rewrite all these scripts to Python 3 soon.

**Comment by stefanv** [comment]
FWIW, I came here for the base64 image encoder.  What I really needed was to embed images inside an HTML, so I wrote this:

https://github.com/elegant-scipy/elegant-scipy/blob/master/tools/html_image_embedder.py

Feel free to use and modify if you find it useful.
